# Dockerfile.dev
FROM mcr.microsoft.com/dotnet/sdk:10.0

RUN dotnet tool install --global dotnet-ef
RUN dotnet tool install --global TeaPie.Tool

ENV PATH="$PATH:/root/.dotnet/tools"

WORKDIR /src/APIKros

EXPOSE 8080

CMD ["dotnet", "watch", "run", "--urls", "http://0.0.0.0:8080"]

