FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY APIKros.csproj .
RUN dotnet restore APIKros.csproj

COPY . .
RUN dotnet publish APIKros.csproj -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS final
WORKDIR /app

COPY --from=build /app/publish .

EXPOSE 5400

ENTRYPOINT ["dotnet", "APIKros.dll"]