### Create Company
# @name CreateCompanyRequest
POST {{APP_URL}}{{CompaniesEndpoint}}
Content-Type: application/json

{{Company}}


### Create Company Clone
# @name CreateCompanyCloneRequest
POST {{APP_URL}}{{CompaniesEndpoint}}
Content-Type: application/json

{{CompanyClone}}


### Create Company Code Clone
# @name CreateCompanyCodeCloneRequest
POST {{APP_URL}}{{CompaniesEndpoint}}
Content-Type: application/json

{{CompanyCodeClone}}


### Create Employee
# @name CreateEmployeeRequest
POST {{APP_URL}}{{EmployeesEndpoint}}
Content-Type: application/json

{
  "employeeNumber": "{{EmployeeEmployeeNumber}}",
  "title": "{{EmployeeTitle}}",
  "firstName": "{{EmployeeFirstName}}",
  "lastName": "{{EmployeeLastName}}",
  "email": "{{EmployeeEmail}}",
  "phone": "{{EmployeePhone}}",
  "companyId": {{CreateCompanyRequest.response.body.$.id}}
}


### Create Employee Clone
# @name CreateEmployeeCloneRequest
POST {{APP_URL}}{{EmployeesEndpoint}}
Content-Type: application/json

{
  "employeeNumber": "{{EmployeeCloneEmployeeNumber}}",
  "title": "{{EmployeeCloneTitle}}",
  "firstName": "{{EmployeeCloneFirstName}}",
  "lastName": "{{EmployeeCloneLastName}}",
  "email": "{{EmployeeCloneEmail}}",
  "phone": "{{EmployeeClonePhone}}",
  "companyId": {{CreateCompanyRequest.response.body.$.id}}
}


### Create Employee Email Clone
# @name CreateEmployeeEmailCloneRequest
POST {{APP_URL}}{{EmployeesEndpoint}}
Content-Type: application/json

{
  "employeeNumber": "{{EmployeeEmailCloneEmployeeNumber}}",
  "title": "{{EmployeeEmailCloneTitle}}",
  "firstName": "{{EmployeeEmailCloneFirstName}}",
  "lastName": "{{EmployeeEmailCloneLastName}}",
  "email": "{{EmployeeEmailCloneEmail}}",
  "phone": "{{EmployeeEmailClonePhone}}",
  "companyId": {{CreateCompanyRequest.response.body.$.id}}
}


### Create Employee Number Clone
# @name CreateEmployeeNumberCloneRequest
POST {{APP_URL}}{{EmployeesEndpoint}}
Content-Type: application/json

{
  "employeeNumber": "{{EmployeeNumberCloneEmployeeNumber}}",
  "title": "{{EmployeeNumberCloneTitle}}",
  "firstName": "{{EmployeeNumberCloneFirstName}}",
  "lastName": "{{EmployeeNumberCloneLastName}}",
  "email": "{{EmployeeNumberCloneEmail}}",
  "phone": "{{EmployeeNumberClonePhone}}",
  "companyId": {{CreateCompanyRequest.response.body.$.id}}
}


### Create Division
# @name CreateDivisionRequest
POST {{APP_URL}}{{DivisionsEndpoint}}
Content-Type: application/json

{
  "name": "{{DivisionName}}",
  "code": "{{DivisionCode}}",
  "managerId": {{CreateEmployeeRequest.response.body.$.id}},
  "parentId": {{CreateCompanyRequest.response.body.$.id}}
}


### Create Division Clone
# @name CreateDivisionCloneRequest
POST {{APP_URL}}{{DivisionsEndpoint}}
Content-Type: application/json

{
  "name": "{{DivisionCloneName}}",
  "code": "{{DivisionCloneCode}}",
  "managerId": {{CreateEmployeeRequest.response.body.$.id}},
  "parentId": {{CreateCompanyRequest.response.body.$.id}}
}


### Create Division Code Clone
# @name CreateDivisionCodeCloneRequest
POST {{APP_URL}}{{DivisionsEndpoint}}
Content-Type: application/json

{
  "name": "{{DivisionCodeCloneName}}",
  "code": "{{DivisionCodeCloneCode}}",
  "managerId": {{CreateEmployeeRequest.response.body.$.id}},
  "parentId": {{CreateCompanyRequest.response.body.$.id}}
}


### Create Project
# @name CreateProjectRequest
POST {{APP_URL}}{{ProjectsEndpoint}}
Content-Type: application/json

{
  "name": "{{ProjectName}}",
  "code": "{{ProjectCode}}",
  "managerId": {{CreateEmployeeRequest.response.body.$.id}},
  "parentId": {{CreateDivisionRequest.response.body.$.id}}
}


### Create Project Clone
# @name CreateProjectCloneRequest
POST {{APP_URL}}{{ProjectsEndpoint}}
Content-Type: application/json

{
  "name": "{{ProjectCloneName}}",
  "code": "{{ProjectCloneCode}}",
  "managerId": {{CreateEmployeeRequest.response.body.$.id}},
  "parentId": {{CreateDivisionRequest.response.body.$.id}}
}


### Create Project Code Clone
# @name CreateProjectCodeCloneRequest
POST {{APP_URL}}{{ProjectsEndpoint}}
Content-Type: application/json

{
  "name": "{{ProjectCodeCloneName}}",
  "code": "{{ProjectCodeCloneCode}}",
  "managerId": {{CreateEmployeeRequest.response.body.$.id}},
  "parentId": {{CreateDivisionRequest.response.body.$.id}}
}


### Create Department
# @name CreateDepartmentRequest
POST {{APP_URL}}{{DepartmentsEndpoint}}
Content-Type: application/json

{
  "name": "{{DepartmentName}}",
  "code": "{{DepartmentCode}}",
  "managerId": {{CreateEmployeeRequest.response.body.$.id}},
  "parentId": {{CreateProjectRequest.response.body.$.id}}
}


### Create Department Clone
# @name CreateDepartmentCloneRequest
POST {{APP_URL}}{{DepartmentsEndpoint}}
Content-Type: application/json

{
  "name": "{{DepartmentCloneName}}",
  "code": "{{DepartmentCloneCode}}",
  "managerId": {{CreateEmployeeRequest.response.body.$.id}},
  "parentId": {{CreateProjectRequest.response.body.$.id}}
}


### Create Department Code Clone
# @name CreateDepartmentCodeCloneRequest
POST {{APP_URL}}{{DepartmentsEndpoint}}
Content-Type: application/json

{
  "name": "{{DepartmentCodeCloneName}}",
  "code": "{{DepartmentCodeCloneCode}}",
  "managerId": {{CreateEmployeeRequest.response.body.$.id}},
  "parentId": {{CreateProjectRequest.response.body.$.id}}
}



### Create Employee Two
# @name CreateEmployee2Request
POST {{APP_URL}}{{EmployeesEndpoint}}
Content-Type: application/json

{
  "employeeNumber": "{{Employee2EmployeeNumber}}",
  "title": "{{Employee2Title}}",
  "firstName": "{{Employee2FirstName}}",
  "lastName": "{{Employee2LastName}}",
  "email": "{{Employee2Email}}",
  "phone": "{{Employee2Phone}}",
  "companyId": {{CreateCompanyRequest.response.body.$.id}}
}


### Create Division Two
# @name CreateDivision2Request
POST {{APP_URL}}{{DivisionsEndpoint}}
Content-Type: application/json

{
  "name": "{{Division2Name}}",
  "code": "{{Division2Code}}",
  "parentId": {{CreateCompanyRequest.response.body.$.id}}
}


### Create Project Two
# @name CreateProject2Request
POST {{APP_URL}}{{ProjectsEndpoint}}
Content-Type: application/json

{
  "name": "{{Project2Name}}",
  "code": "{{Project2Code}}",
  "parentId": {{CreateDivision2Request.response.body.$.id}}
}


### Create Department Two
# @name CreateDepartment2Request
POST {{APP_URL}}{{DepartmentsEndpoint}}
Content-Type: application/json

{
  "name": "{{Department2Name}}",
  "code": "{{Department2Code}}",
  "parentId": {{CreateProject2Request.response.body.$.id}}
}

### Update Employee Email Clone Violation

# @name UpdateEmployeeEmailCloneRequest

PUT {{APP_URL}}{{EmployeesEndpoint}}/{{CreateEmployee2Request.response.body.$.id}}
Content-Type: application/json

{
  "email": "{{EmployeeEmail}}",
  "employeeNumber": "{{Employee2EmployeeNumber}}",
  "firstName": "{{Employee2FirstName}}",
  "lastName": "{{Employee2LastName}}",
  "title": "{{Employee2Title}}",
  "phone": "{{Employee2Phone}}",
  "companyId": {{CreateCompanyRequest.response.body.$.id}}
}

### Update Employee Number Clone Violation

# @name UpdateEmployeeNumberCloneRequest

PUT {{APP_URL}}{{EmployeesEndpoint}}/{{CreateEmployee2Request.response.body.$.id}}
Content-Type: application/json

{
  "email": "{{Employee2Email}}",
  "employeeNumber": "{{EmployeeEmployeeNumber}}",
  "firstName": "{{Employee2FirstName}}",
  "lastName": "{{Employee2LastName}}",
  "title": "{{Employee2Title}}",
  "phone": "{{Employee2Phone}}",
  "companyId": {{CreateCompanyRequest.response.body.$.id}}
}

### Update Division Code Clone Violation

# @name UpdateDivisionCodeCloneRequest

PUT {{APP_URL}}{{DivisionsEndpoint}}/{{CreateDivision2Request.response.body.$.id}}
Content-Type: application/json

{
  "name": "{{Division2Name}}",
  "code": "{{DivisionCode}}",
  "managerId": {{CreateEmployeeRequest.response.body.$.id}},
  "parentId": {{CreateCompanyRequest.response.body.$.id}}
}

### Update Project Code Clone Violation

# @name UpdateProjectCodeCloneRequest

PUT {{APP_URL}}{{ProjectsEndpoint}}/{{CreateProject2Request.response.body.$.id}}
Content-Type: application/json

{
  "name": "{{Project2Name}}",
  "code": "{{ProjectCode}}",
  "managerId": {{CreateEmployeeRequest.response.body.$.id}},
  "parentId": {{CreateDivisionRequest.response.body.$.id}}
}

### Update Department Code Clone Violation

# @name UpdateDepartmentCodeCloneRequest

PUT {{APP_URL}}{{DepartmentsEndpoint}}/{{CreateDepartment2Request.response.body.$.id}}
Content-Type: application/json

{
  "name": "{{Department2Name}}",
  "code": "{{DepartmentCode}}",
  "managerId": {{CreateEmployeeRequest.response.body.$.id}},
  "parentId": {{CreateProjectRequest.response.body.$.id}}
}



### Delete Department Two
# @name DeleteDepartment2Request
DELETE {{APP_URL}}{{DepartmentsEndpoint}}/{{CreateDepartment2Request.response.body.$.id}}


### Delete Project Two
# @name DeleteProject2Request
DELETE {{APP_URL}}{{ProjectsEndpoint}}/{{CreateProject2Request.response.body.$.id}}


### Delete Division Two
# @name DeleteDivision2Request
DELETE {{APP_URL}}{{DivisionsEndpoint}}/{{CreateDivision2Request.response.body.$.id}}


### Delete Employee Two
# @name DeleteEmployee2Request
DELETE {{APP_URL}}{{EmployeesEndpoint}}/{{CreateEmployee2Request.response.body.$.id}}



### Delete Department
# @name DeleteDepartmentRequest
DELETE {{APP_URL}}{{DepartmentsEndpoint}}/{{CreateDepartmentRequest.response.body.$.id}}


### Delete Project
# @name DeleteProjectRequest
DELETE {{APP_URL}}{{ProjectsEndpoint}}/{{CreateProjectRequest.response.body.$.id}}


### Delete Division
# @name DeleteDivisionRequest
DELETE {{APP_URL}}{{DivisionsEndpoint}}/{{CreateDivisionRequest.response.body.$.id}}


### Delete Employee
# @name DeleteEmployeeRequest
DELETE {{APP_URL}}{{EmployeesEndpoint}}/{{CreateEmployeeRequest.response.body.$.id}}

### Delete Company
# @name DeleteCompanyRequest
DELETE {{APP_URL}}{{CompaniesEndpoint}}/{{CreateCompanyRequest.response.body.$.id}}

